NumPy: 
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [2]:
import numpy as np
# creating arrays using numpy
# creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5, 6]) #we can give list or tuple or any array-like structure as input
print("1D Array:", arr1)
print("Type of arr1:", type(arr1))
print("Shape of arr1:", arr1.shape)

1D Array: [1 2 3 4 5 6]
Type of arr1: <class 'numpy.ndarray'>
Shape of arr1: (6,)


In [5]:
#Now we want to convert this 1D array into a 2D array
arr2 = arr1.reshape(2, 3) #2 rows and 3 columns
print("2D Array:\n", arr2)
print("Shape of arr2:", arr2.shape)

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape of arr2: (2, 3)


In [8]:
#Creating arrays with inbuilt functions
arr3 = np.arange(0, 10, 2) #start, end, step
print("Array using arange():", arr3)

arr3 = np.arange(0, 10, 2).reshape(5, 1) #reshaping to 2D array
print("Reshaped Array using arange():\n", arr3)

Array using arange(): [0 2 4 6 8]
Reshaped Array using arange():
 [[0]
 [2]
 [4]
 [6]
 [8]]


In [9]:
#Inbuilt functions in numpy
npOne = np.ones((3, 4))
print("Array of ones:\n", npOne)

Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Identity matrix
npEye = np.eye(4) #all the diagonal elements are 1, rest are 0
print("Identity Matrix:\n", npEye)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Array attributes
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Size (number of elements):", arr.size) #total number of elements
print("Number of Dimensions:", arr.ndim)
print("Data Type:", arr.dtype) #data type of elements in array
print("Item Size (in bytes):", arr.itemsize) #size of each element in bytes
print("Total Bytes:", arr.nbytes) #size * itemsize 

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size (number of elements): 6
Number of Dimensions: 2
Data Type: int32
Item Size (in bytes): 4
Total Bytes: 24


In [13]:
# Numpy Vectorized Operations: operations performed element-wise
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element-wise addition
sum_arr = arr1 + arr2 # adds corresponding elements of arr1 and arr2 like [1+10, 2+20, 3+30, ...]
print("Element-wise Addition:", sum_arr)

# Element-wise subtraction
print("Element-wise Subtraction:", arr2 - arr1)

# Element-wise multiplication
print("Element-wise Multiplication:", arr1 * arr2)

# Element-wise division
print("Element-wise Division:", arr2 / arr1)

Element-wise Addition: [11 22 33 44 55]
Element-wise Subtraction: [ 9 18 27 36 45]
Element-wise Multiplication: [ 10  40  90 160 250]
Element-wise Division: [10. 10. 10. 10. 10.]


In [29]:
# Universal Functions (ufuncs)
arr = np.array([2, 3, 4, 5])

# we are using np module to access these functions and not the arr object as these are not methods of the array object, but functions provided by numpy for array operations.

# when we do arr = np.array([...]), arr is an instance of numpy.ndarray class, which represents an array. The functions like np.sqrt(), np.exp(), np.sin() are universal functions (ufuncs) provided by the numpy library that operate element-wise on arrays.

# Square root
print("Square Root:", np.sqrt(arr))

# Exponential
print("Exponential:", np.exp(arr))

# Sine
print("Sine:", np.sin(arr))

# Logarithm
print("Logarithm:", np.log(arr))


Square Root: [1.41421356 1.73205081 2.         2.23606798]
Exponential: [  7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine: [ 0.90929743  0.14112001 -0.7568025  -0.95892427]
Logarithm: [0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
# array slicing and indexing

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original Array:\n", arr)
# Accessing elements
print("Element at (0,0):", arr[0, 0]) #first row, first column
print("Element at (1,2):", arr[1][2]) #second row, third column 

#now suppose we want from element 7 8 11 12 
print("Elements from (1,2) to end:\n", arr[1:, 2:]) #so from the second row and third column onwards

# for 3 4 7 8
print(arr[0:2, 2:])

# for 6 7 10 11
print(arr[1:,1:3])


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at (0,0): 1
Element at (1,2): 7
Elements from (1,2) to end:
 [[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [18]:
# Modifying elements
arr[0, 0] = 99
print("Modified Array:\n", arr)

arr2 = arr.copy() #to create a copy of the array
arr2[1:] = 0
print("Array after modifying copy:\n", arr2)
print("Original Array remains unchanged:\n", arr)

Modified Array:
 [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array after modifying copy:
 [[99  2  3  4]
 [ 0  0  0  0]
 [ 0  0  0  0]]
Original Array remains unchanged:
 [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
# statistics with numpy --normally we use pandas for statistics but numpy also provides some basic statistical functions
# normalization, mean, median, std deviation, variance etc.
#normalization: to have a mean of 0 and std deviation of 1

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(data)
std_dev = np.std(data)
normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)

Normalized Data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [23]:
# mean, median, variance, std deviation
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Variance:", np.var(data))
print("Standard Deviation:", np.std(data))


Mean: 5.5
Median: 5.5
Variance: 8.25
Standard Deviation: 2.8722813232690143


In [ ]:
#Logical operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Elements greater than 20:", data[data > 5]) # we use boolean indexing to filter elements based on a condition  
print(data>5)

print(data[(data>=5) & (data<=8)])


Elements greater than 20: [ 6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[5 6 7 8]
